import NavBar from '../components/navbar/NavBar';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Wuilmer's Home Page",
  description: 'Generated by Vercel next app',
}

export default function RootLayout({ children }: { children: React.ReactNode}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        
        {children}
    
      </body>
    </html>
  )
}
